name: UI Automation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Build project
        run: ./gradlew build --no-daemon

      - name: Run Selenium tests (headless)
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export CHROMEDRIVER=/usr/bin/chromedriver
          ./gradlew test --no-daemon -Dwebdriver.chrome.driver=$CHROMEDRIVER

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
